esphome:
  name: display-test-controller
  friendly_name: display_test

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  framework:
    type: esp-idf

external_components:
  - source: 
      type: git
      url: https://github.com/obucklin/GDEP073E01_DisplayComponent
    components: all

logger:
  level: VERBOSE

api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Display-Test Fallback Hotspot"
    password: ""  

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19  # MOSI is required

display:
  - platform: gdep073e01
    cs_pin: GPIO0
    dc_pin: GPIO1
    reset_pin: GPIO3
    busy_pin: GPIO2  # Input pin
    full_update_every: 30
    lambda: |-
      it.fill(esphome::display::COLOR_ON);
      
captive_portal:    
    
    