esphome:
  name: table-lamp
  friendly_name: table_lamp

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "kO+Hg9bcHgdAIUP+V0I8QRYVB8jZON01Atjwy+kFFMI="

ota:
  - platform: esphome
    password: "e3f19d8a9d5e65b2c60312c00fec12e6"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Table-Lamp Fallback Hotspot"
    password: "Nji2uNqpma90"

light:
  - platform: neopixelbus
    num_leds: 7
    type: GRB
    variant: ws2812x
    id: table_lamp
    pin: GPIO10
  - platform: partition
    name: "Ring #2"
    segments:
      - id: table_lamp
        from: 0
        to: 6 
    effects:
      - addressable_flicker: 
      - addressable_twinkle: 
      - pulse: 
      - flicker:
            
          
    internal: false







captive_portal:
    