esphome:
  name: test
  friendly_name: test

esp32:
  platform: esp-idf
  board: esp32dev

    

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "GhO1FBUnOrlUSeEntqmRcSKckIzGndszEDEC7tAX38w="

ota:
  - platform: esphome
    password: "af1cece3fe425b031a0462db73614178"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "tvFIiASCPpfK"

captive_portal:
    